#    Copyright CodeMerx 2020
#    This file is part of CodemerxDecompile.

#    CodemerxDecompile is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    CodemerxDecompile is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with CodemerxDecompile.  If not, see<https://www.gnu.org/licenses/>.

name: Package-old

env:
  NODE_VERSION: 10.22.1
  GITHUB_TOKEN: ${{ secrets.CD_API_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      windows:
        description: 'Windows'
        required: false
        default: true
      linux:
        description: 'Linux'
        required: false
        default: true
      macos:
        description: 'MacOS'
        required: false
        default: true

jobs:
  package-linux:
    if: ${{ github.event.inputs.linux }}
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn
      working-directory: ./ui

    - name: Restore SNK
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/common/CDKey.snk
        encodedString: ${{ secrets.CD_SNK }}

    - name: Package
      run: gulp vscode-linux-x64
      working-directory: ./ui
      env:
        NODE_OPTIONS: --max-old-space-size=8192

    - name: Archive artifacts
      run: tar -czpvf CodemerxDecompile-linux-x64.tar.gz ./CodemerxDecompile-linux-x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CodemerxDecompile-linux-x64
        path: CodemerxDecompile-linux-x64.tar.gz

  package-windows:
    if: ${{ github.event.inputs.windows }}
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn
      working-directory: ./ui

    - name: Restore SNK
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/common/CDKey.snk
        encodedString: ${{ secrets.CD_SNK }}

    - name: Package
      run: gulp vscode-win32-x64
      working-directory: ./ui
      env:
        NODE_OPTIONS: --max-old-space-size=8192

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CodemerxDecompile-win32-x64
        path: CodemerxDecompile-win32-x64

  package-macos:
    if: ${{ github.event.inputs.macos }}
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Gulp CLI
      run: npm install --global gulp-cli

    - name: Install Dependencies
      run: yarn
      working-directory: ./ui

    - name: Restore SNK
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/common/CDKey.snk
        encodedString: ${{ secrets.CD_SNK }}

    - name: Package
      run: gulp vscode-darwin
      working-directory: ./ui
      env:
        NODE_OPTIONS: --max-old-space-size=8192

    - name: Archive artifacts
      run: tar -czpvf CodemerxDecompile-darwin.tar.gz ./CodemerxDecompile-darwin

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CodemerxDecompile-darwin
        path: CodemerxDecompile-darwin.tar.gz
